"use client";

import { useEffect, useRef, useState } from "react";
import { useGSAP } from "@gsap/react";
import gsap from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";

gsap.registerPlugin(ScrollTrigger);

/**
 * Division hero — a WebP frame sequence scrubbed by scroll position.
 *
 * Frames are generated by scripts/extract_hero_frames.py (see that file for why
 * a frame sequence is used instead of scrubbing the video's currentTime).
 *
 * Structure: a tall scroll track containing a `sticky` viewport-height stage.
 * CSS sticky does the pinning rather than ScrollTrigger's `pin`, which avoids
 * the pin-spacer remeasurement problems the rest of the page works around;
 * ScrollTrigger is used only to read progress. Lenis and ScrollTrigger already
 * share a clock (see components/motion/SmoothScroll.tsx), so progress stays in
 * sync with the smooth-scrolled position.
 *
 * Loading: the first frame renders immediately as a plain <img> poster so the
 * hero is never blank, and the remaining frames stream in behind it with a
 * capped number of parallel requests. Scrubbing only switches on once every
 * frame is decoded — a partly-loaded sequence would jump back to a stale frame
 * whenever the user outran the downloads. The sequence is large (see the
 * script's header), so nothing here blocks page interaction while it fills.
 *
 * The copy sits centred over the stage — true centre (both axes) below `lg`,
 * where there's no room to spare; bottom-aligned with room reserved for the
 * scroll cue from `lg` up. It slides up out of the way as soon as scrolling
 * starts, handing the screen to the footage. `tone` picks the text colour per
 * division because the sequences differ: the buildings clip opens on a white
 * frame (measured luminance 255) and the oil clip on a dark blue one (~104),
 * so a single colour can't serve both.
 *
 * `motion-reduce` collapses the scroll track to a single screen via CSS (no
 * layout shift, since it never depends on JS). Reduced-motion and Save-Data
 * users skip the frame preload entirely and are marked ready immediately —
 * they get the static poster and never see the loading gate below.
 *
 * Loading gate: the whole page (not just the hero) is hidden behind a
 * fixed, full-viewport overlay until every frame has decoded — the request
 * this is built for is "these pages load only once the animation is ready",
 * so a page half-visible behind a partial hero would defeat the point. Scroll
 * is locked for the same reason. This is a genuine trade-off: the gate adds
 * a hard wait (see scripts/extract_hero_frames.py for payload size) before
 * anything on the page is visible or indexable-looking to a visitor, in
 * exchange for never showing an unfinished hero.
 */
export function DivisionHero({
  dir,
  count,
  name,
  tagline,
  tone = "light",
  children,
}: {
  /** Public path of the frame directory, e.g. "/division-frames/building". */
  dir: string;
  /** Number of frames in the sequence (files are 0001.webp … NNNN.webp). */
  count: number;
  name: string;
  tagline: string;
  /** Ink colour for the overlaid copy — set from the opening frame's brightness. */
  tone?: "light" | "dark";
  /** Overlaid hero copy. */
  children?: React.ReactNode;
}) {
  const track = useRef<HTMLElement>(null);
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const copyRef = useRef<HTMLDivElement>(null);
  const cueRef = useRef<HTMLDivElement>(null);
  const framesRef = useRef<HTMLImageElement[]>([]);
  const drawnRef = useRef(-1);
  const [ready, setReady] = useState(false);
  const [progress, setProgress] = useState(0);

  const dark = tone === "dark";

  // Green-accent the final word of the division name and leave the rest in
  // ink, matching the split-colour headings used across the site. Splitting on
  // the last space keeps it data-driven — "Buildings & Infrastructure" and
  // "Oil & Gas" both land on a sensible word with no per-division config.
  const lastSpace = name.lastIndexOf(" ");
  const head = lastSpace > 0 ? name.slice(0, lastSpace + 1) : name;
  const tail = lastSpace > 0 ? name.slice(lastSpace + 1) : "";

  const src = (i: number) => `${dir}/${String(i + 1).padStart(4, "0")}.webp`;

  // ── Preload ──────────────────────────────────────────────────────────────
  useEffect(() => {
    const mq = window.matchMedia("(prefers-reduced-motion: reduce)");
    const conn = (
      navigator as Navigator & { connection?: { saveData?: boolean } }
    ).connection;
    if (mq.matches || conn?.saveData) {
      // These users never get the animated sequence — they keep the static
      // poster. Mark ready immediately rather than leaving it false forever:
      // `ready` now also lifts the full-page loading gate below, and that
      // gate must never hang open for someone who was never going to trigger
      // the preload that would otherwise flip it.
      setReady(true);
      return;
    }

    let cancelled = false;
    const images: HTMLImageElement[] = new Array(count);

    const load = (i: number) =>
      new Promise<void>((resolve) => {
        const img = new Image();
        // Decode off the main thread where supported so the first scrub isn't
        // stalled by 274 synchronous decodes.
        img.decoding = "async";
        img.onload = img.onerror = () => {
          images[i] = img;
          resolve();
        };
        img.src = src(i);
      });

    // Cap parallelism: firing every request at once buys nothing over HTTP/2
    // and starves the rest of the page's assets (fonts, below-fold images).
    const CONCURRENCY = 10;
    let next = 0;
    let done = 0;

    const worker = async (): Promise<void> => {
      while (!cancelled && next < count) {
        const i = next++;
        await load(i);
        done++;
        if (!cancelled && done % 5 === 0) setProgress(done / count);
      }
    };

    Promise.all(Array.from({ length: CONCURRENCY }, worker)).then(() => {
      if (cancelled) return;
      framesRef.current = images;
      setProgress(1);
      setReady(true);
    });

    return () => {
      cancelled = true;
    };
  }, [dir, count]); // eslint-disable-line react-hooks/exhaustive-deps

  // ── Loading-gate scroll lock ──────────────────────────────────────────────
  // Blocks scrolling past the gate while it's up. Runs on `document.body`
  // rather than the track itself since the gate covers the whole page, not
  // just this section.
  useEffect(() => {
    if (ready) return;
    const prev = document.body.style.overflow;
    document.body.style.overflow = "hidden";
    return () => {
      document.body.style.overflow = prev;
    };
  }, [ready]);

  // ── Copy slide-away + scroll cue ─────────────────────────────────────────
  // Independent of the frame preload: the copy must react to scroll from the
  // first paint, long before 20-25 MB of frames has finished decoding.
  useGSAP(
    () => {
      const el = track.current;
      if (!el || !copyRef.current) return;
      if (window.matchMedia("(prefers-reduced-motion: reduce)").matches) return;

      // Lift and fade the copy away as scrolling starts. The 18% end is set by
      // the footage, not taste: the oil clip's lower band drops from 255 to
      // ~140 luminance by 18% and ~100 by 22%, so dark copy has to be gone
      // before then to stay legible. Buildings stays bright throughout, so the
      // shared value is driven by the tighter of the two.
      gsap.to(copyRef.current, {
        yPercent: -40,
        opacity: 0,
        ease: "none",
        scrollTrigger: {
          trigger: el,
          start: "top top",
          end: "18% top",
          scrub: true,
        },
      });

      // The cue sits apart from the copy at the foot of the stage, so it fades
      // on its own — and faster, since it has served its purpose the moment
      // scrolling begins.
      if (cueRef.current) {
        gsap.to(cueRef.current, {
          opacity: 0,
          ease: "none",
          scrollTrigger: {
            trigger: el,
            start: "top top",
            end: "8% top",
            scrub: true,
          },
        });
      }
    },
    { scope: track },
  );

  // ── Draw + scrub ─────────────────────────────────────────────────────────
  useGSAP(
    () => {
      if (!ready) return;
      const canvas = canvasRef.current;
      const el = track.current;
      if (!canvas || !el) return;
      const ctx = canvas.getContext("2d", { alpha: false });
      if (!ctx) return;

      // Cover-fit the frame into the canvas box, matching object-cover.
      const draw = (index: number) => {
        const img = framesRef.current[index];
        if (!img?.width) return;
        const dpr = Math.min(window.devicePixelRatio || 1, 2);
        const cw = canvas.clientWidth;
        const ch = canvas.clientHeight;
        if (canvas.width !== Math.round(cw * dpr)) {
          canvas.width = Math.round(cw * dpr);
          canvas.height = Math.round(ch * dpr);
        }
        const scale = Math.max(cw / img.width, ch / img.height);
        const w = img.width * scale;
        const h = img.height * scale;
        ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
        ctx.drawImage(img, (cw - w) / 2, (ch - h) / 2, w, h);
        drawnRef.current = index;
      };

      draw(0);

      const st = ScrollTrigger.create({
        trigger: el,
        start: "top top",
        end: "bottom bottom",
        onUpdate: (self) => {
          const i = Math.min(
            count - 1,
            Math.max(0, Math.round(self.progress * (count - 1))),
          );
          if (i !== drawnRef.current) draw(i);
        },
      });

      const onResize = () => {
        // Force a re-fit: clientWidth changed, so the cached canvas backing
        // size and the cover scale are both stale.
        canvas.width = 0;
        draw(drawnRef.current < 0 ? 0 : drawnRef.current);
      };
      window.addEventListener("resize", onResize);

      return () => {
        st.kill();
        window.removeEventListener("resize", onResize);
      };
    },
    { dependencies: [ready, count], scope: track },
  );

  return (
    <>
      {/* Loading gate — fixed to the viewport (not this section), so it
          covers the whole page regardless of where DivisionHero sits in the
          tree. Fades out once every frame has decoded; see the file header
          for why the whole page waits on this rather than just the hero. */}
      <div
        aria-hidden={ready}
        className={`fixed inset-0 z-[100] flex flex-col items-center justify-center gap-5 bg-navy transition-opacity duration-500 ${
          ready ? "pointer-events-none opacity-0" : "opacity-100"
        }`}
      >
        <img src="/logo.webp" alt="" width={462} height={200} className="h-9 w-auto object-contain" />
        <div className="h-0.5 w-40 overflow-hidden rounded-full bg-paper/15">
          <div
            className="h-full bg-green transition-[width] duration-200 ease-out"
            style={{ width: `${Math.round(progress * 100)}%` }}
          />
        </div>
        <p className="font-mono text-[0.62rem] uppercase tracking-[0.2em] text-paper/50">
          Loading {Math.round(progress * 100)}%
        </p>
      </div>

      <section
        ref={track}
        className="relative h-[260vh] motion-reduce:h-screen"
        aria-label={`${name} — scroll-driven hero`}
      >
      <div className="sticky top-0 flex h-screen items-center overflow-hidden lg:items-end">
        {/* Poster: the first frame, shown until the sequence is decoded. */}
        <img
          src={src(0)}
          alt={name}
          fetchPriority="high"
          className={`absolute inset-0 h-full w-full object-cover transition-opacity duration-500 ${
            ready ? "opacity-0" : "opacity-100"
          }`}
        />
        <canvas
          ref={canvasRef}
          aria-hidden
          className={`absolute inset-0 h-full w-full transition-opacity duration-500 ${
            ready ? "opacity-100" : "opacity-0"
          }`}
        />

        <div
          ref={copyRef}
          className="relative mx-auto w-full max-w-[1600px] px-6 text-center will-change-transform md:px-10 lg:pb-52 xl:pb-60"
        >
          {children ?? (
            <>
              <h1
                className={`mx-auto max-w-4xl font-display text-[clamp(2.5rem,1rem+5vw,5.5rem)] font-semibold leading-[1.03] tracking-[-0.02em] lg:flex lg:min-h-[2lh] lg:flex-col lg:justify-end ${
                  dark ? "text-ink" : "text-paper"
                }`}
                style={{
                  textShadow: dark
                    ? "0 1px 24px rgba(247,245,242,0.75)"
                    : "0 2px 30px rgba(9,33,44,0.45)",
                }}
              >
                {head}
                {tail && <span className="text-green-dark">{tail}</span>}
              </h1>
              <p
                className={`mx-auto mt-6 max-w-2xl text-lg leading-relaxed md:text-xl ${
                  dark ? "text-ink/75" : "text-paper"
                }`}
                style={{
                  textShadow: dark
                    ? "0 1px 18px rgba(247,245,242,0.8)"
                    : "0 1px 18px rgba(9,33,44,0.55)",
                }}
              >
                {tagline}
              </p>
            </>
          )}
        </div>

        {/* Scroll cue — mouse outline with a drifting wheel dot, parked at the
            foot of the stage rather than under the copy, so it reads as a
            viewport affordance instead of part of the heading block. */}
        <div
          ref={cueRef}
          aria-hidden
          className={`absolute bottom-8 left-1/2 -translate-x-1/2 md:bottom-10 ${
            dark ? "text-ink/60" : "text-paper/80"
          }`}
        >
          <span className="flex h-10 w-6 items-start justify-center rounded-full border-2 border-current pt-2">
            <span className="block h-1.5 w-1 rounded-full bg-current animate-scroll-cue motion-reduce:animate-none" />
          </span>
        </div>
      </div>
      </section>
    </>
  );
}
