"use client";

import { useEffect, useRef, useState } from "react";
import { useGSAP } from "@gsap/react";
import gsap from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";

gsap.registerPlugin(ScrollTrigger);

/** A frame sequence mid-flight or fully decoded. `ready` is the number of
 * frames decoded *contiguously* from 0 — the sequence is scrubbable up to
 * `ready - 1` and unknown beyond it. Frames past the watermark may well be
 * decoded (the loader runs a pool, so they land out of order) but can't be
 * relied on, hence a single watermark rather than a per-frame check. */
type FrameSet = { images: HTMLImageElement[]; ready: number };

/** Module-level (not component-level) so it survives an unmount/remount —
 * i.e. navigating away from a division page and back within the same soft
 * (client-side) navigation session resumes from the frames already decoded
 * instead of redoing the work. A revisit after a completed load skips the
 * gate entirely; a revisit that interrupted the load part-way picks up at the
 * watermark. This only helps within one session; it can't survive a hard page
 * reload, which is what converting internal links to next/link (see Navbar,
 * Footer, DivisionView's cross-link, etc.) is for — this cache is the other
 * half of that fix. */
const frameCache = new Map<string, FrameSet>();

/**
 * Frames that must be decoded before the loading gate lifts. The rest keep
 * streaming in behind the now-visible page.
 *
 * The gate exists so nobody sees an unfinished hero, but that doesn't require
 * the *whole* sequence — only enough of a head start that scrubbing has
 * somewhere to go. 48 of ~274 frames is ~4 MB rather than ~24 MB, so the page
 * appears roughly 5-6x sooner, and covers the first ~28vh of scrolling.
 *
 * Outrunning the buffer is still possible (a trackpad flick can cover 200
 * frames' worth of track in one gesture, which no buffer survives on a slow
 * connection) — that's what the watermark clamp in the scrub handler is for:
 * the hero holds on the newest decoded frame and catches up, instead of
 * snapping back to a stale one.
 */
const GATE_FRAMES = 48;

/**
 * Division hero — a WebP frame sequence scrubbed by scroll position.
 *
 * Frames are generated by scripts/extract_hero_frames.py (see that file for why
 * a frame sequence is used instead of scrubbing the video's currentTime).
 *
 * Structure: a tall scroll track containing a `sticky` viewport-height stage.
 * CSS sticky does the pinning rather than ScrollTrigger's `pin`, which avoids
 * the pin-spacer remeasurement problems the rest of the page works around;
 * ScrollTrigger is used only to read progress. Lenis and ScrollTrigger already
 * share a clock (see components/motion/SmoothScroll.tsx), so progress stays in
 * sync with the smooth-scrolled position.
 *
 * Loading: the first frame renders immediately as a plain <img> poster so the
 * hero is never blank, and the rest stream in behind it with a capped number of
 * parallel requests, in order. Scrubbing switches on after GATE_FRAMES and is
 * clamped to the contiguous-decoded watermark, so a partly-loaded sequence
 * holds on its newest frame rather than jumping back to a stale one; the
 * loader nudges it forward as the watermark advances, since scroll events
 * alone wouldn't redraw a hero the user has already stopped scrolling past.
 *
 * The copy sits centred over the stage — true centre (both axes) below `lg`,
 * where there's no room to spare; bottom-aligned with room reserved for the
 * scroll cue from `lg` up. It slides up out of the way as soon as scrolling
 * starts, handing the screen to the footage. `tone` picks the text colour per
 * division because the sequences differ: the buildings clip opens on a white
 * frame (measured luminance 255) and the oil clip on a dark blue one (~104),
 * so a single colour can't serve both.
 *
 * `motion-reduce` collapses the scroll track to a single screen via CSS (no
 * layout shift, since it never depends on JS). Reduced-motion and Save-Data
 * users skip the frame preload entirely and are marked ready immediately —
 * they get the static poster and never see the loading gate below.
 *
 * Loading gate: the whole page (not just the hero) is hidden behind a fixed,
 * full-viewport overlay until the hero can animate — the request this is built
 * for is "these pages load only once the animation is ready", so a page
 * half-visible behind a partial hero would defeat the point. Scroll is locked
 * for the same reason. The wait is bounded by GATE_FRAMES rather than the whole
 * sequence, which is what keeps that guarantee affordable.
 */
export function DivisionHero({
  dir,
  count,
  name,
  tagline,
  tone = "light",
  children,
}: {
  /** Public path of the frame directory, e.g. "/division-frames/building". */
  dir: string;
  /** Number of frames in the sequence (files are 0001.webp … NNNN.webp). */
  count: number;
  name: string;
  tagline: string;
  /** Ink colour for the overlaid copy — set from the opening frame's brightness. */
  tone?: "light" | "dark";
  /** Overlaid hero copy. */
  children?: React.ReactNode;
}) {
  const track = useRef<HTMLElement>(null);
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const copyRef = useRef<HTMLDivElement>(null);
  const cueRef = useRef<HTMLDivElement>(null);
  const framesRef = useRef<HTMLImageElement[]>([]);
  const drawnRef = useRef(-1);
  /** Highest frame index safe to draw — see FrameSet.ready. A ref, not state,
   * so the loader can advance it ~274 times without re-rendering; the scrub
   * handler reads it at draw time. */
  const readyUpToRef = useRef(-1);
  /** Set by the scrub effect: redraw at the current scroll position. Called by
   * the loader so a hero that outran its buffer catches up even when the user
   * has stopped scrolling (no scroll events = no onUpdate = no redraw). */
  const catchUpRef = useRef<(() => void) | null>(null);
  const [ready, setReady] = useState(false);
  const [progress, setProgress] = useState(0);

  const dark = tone === "dark";

  // Green-accent the final word of the division name and leave the rest in
  // ink, matching the split-colour headings used across the site. Splitting on
  // the last space keeps it data-driven — "Buildings & Infrastructure" and
  // "Oil & Gas" both land on a sensible word with no per-division config.
  const lastSpace = name.lastIndexOf(" ");
  const head = lastSpace > 0 ? name.slice(0, lastSpace + 1) : name;
  const tail = lastSpace > 0 ? name.slice(lastSpace + 1) : "";

  const src = (i: number) => `${dir}/${String(i + 1).padStart(4, "0")}.webp`;

  // ── Preload ──────────────────────────────────────────────────────────────
  useEffect(() => {
    const mq = window.matchMedia("(prefers-reduced-motion: reduce)");
    const conn = (
      navigator as Navigator & { connection?: { saveData?: boolean } }
    ).connection;
    if (mq.matches || conn?.saveData) {
      // These users never get the animated sequence — they keep the static
      // poster. Mark ready immediately rather than leaving it false forever:
      // `ready` now also lifts the full-page loading gate below, and that
      // gate must never hang open for someone who was never going to trigger
      // the preload that would otherwise flip it.
      setReady(true);
      return;
    }

    // Adopt whatever this session already decoded for this sequence (a revisit
    // to the page, possibly one that was interrupted part-way) and carry on
    // from its watermark. A `const` binding, so the narrowing survives into the
    // worker closures below.
    const existing = frameCache.get(dir);
    const frames: FrameSet =
      existing && existing.images.length === count
        ? existing
        : { images: new Array(count), ready: 0 };
    frameCache.set(dir, frames);

    const { images } = frames;
    framesRef.current = images;
    readyUpToRef.current = frames.ready - 1;

    const gate = Math.min(count, GATE_FRAMES);
    let lifted = frames.ready >= gate;
    if (lifted) {
      setProgress(1);
      setReady(true);
    } else {
      setProgress(frames.ready / gate);
    }
    if (frames.ready >= count) return; // fully decoded earlier — nothing to do

    let cancelled = false;

    const load = (i: number) =>
      new Promise<void>((resolve) => {
        const img = new Image();
        // Decode off the main thread where supported so the first scrub isn't
        // stalled by 274 synchronous decodes.
        img.decoding = "async";
        img.onload = img.onerror = () => {
          images[i] = img;
          resolve();
        };
        img.src = src(i);
      });

    // Walk the watermark forward over any newly-contiguous run. Frames land out
    // of order within the pool, so one arrival can advance it by several.
    const advance = () => {
      while (frames.ready < count && images[frames.ready]) frames.ready++;
      readyUpToRef.current = frames.ready - 1;
    };

    // Cap parallelism: firing every request at once buys nothing over HTTP/2
    // and starves the rest of the page's assets (fonts, below-fold images).
    const CONCURRENCY = 10;
    // Hand out indices in order — scroll only ever moves forward through the
    // sequence, so in-order is also priority order.
    let next = frames.ready;

    const worker = async (): Promise<void> => {
      while (!cancelled) {
        const i = next++;
        if (i >= count) return;
        if (!images[i]) await load(i);
        if (cancelled) return;

        const before = frames.ready;
        advance();
        if (frames.ready === before) continue; // filled a hole ahead, not the edge

        if (!lifted && frames.ready >= gate) {
          lifted = true;
          setProgress(1);
          setReady(true);
        } else if (lifted) {
          // More of the sequence is now scrubbable; pull the hero forward if it
          // was waiting on it.
          catchUpRef.current?.();
        } else {
          setProgress(frames.ready / gate);
        }
      }
    };

    void Promise.all(Array.from({ length: CONCURRENCY }, worker));

    return () => {
      cancelled = true;
    };
  }, [dir, count]); // eslint-disable-line react-hooks/exhaustive-deps

  // ── Loading-gate scroll lock ──────────────────────────────────────────────
  // Blocks scrolling past the gate while it's up. Runs on `document.body`
  // rather than the track itself since the gate covers the whole page, not
  // just this section.
  useEffect(() => {
    if (ready) return;
    const prev = document.body.style.overflow;
    document.body.style.overflow = "hidden";
    return () => {
      document.body.style.overflow = prev;
    };
  }, [ready]);

  // ── Copy slide-away + scroll cue ─────────────────────────────────────────
  // Independent of the frame preload: the copy must react to scroll from the
  // first paint, long before 20-25 MB of frames has finished decoding.
  useGSAP(
    () => {
      const el = track.current;
      if (!el || !copyRef.current) return;
      if (window.matchMedia("(prefers-reduced-motion: reduce)").matches) return;

      // Lift and fade the copy away as scrolling starts. The 18% end is set by
      // the footage, not taste: the oil clip's lower band drops from 255 to
      // ~140 luminance by 18% and ~100 by 22%, so dark copy has to be gone
      // before then to stay legible. Buildings stays bright throughout, so the
      // shared value is driven by the tighter of the two.
      gsap.to(copyRef.current, {
        yPercent: -40,
        opacity: 0,
        ease: "none",
        scrollTrigger: {
          trigger: el,
          start: "top top",
          end: "18% top",
          scrub: true,
        },
      });

      // The cue sits apart from the copy at the foot of the stage, so it fades
      // on its own — and faster, since it has served its purpose the moment
      // scrolling begins.
      if (cueRef.current) {
        gsap.to(cueRef.current, {
          opacity: 0,
          ease: "none",
          scrollTrigger: {
            trigger: el,
            start: "top top",
            end: "8% top",
            scrub: true,
          },
        });
      }
    },
    { scope: track },
  );

  // ── Draw + scrub ─────────────────────────────────────────────────────────
  useGSAP(
    () => {
      if (!ready) return;
      const canvas = canvasRef.current;
      const el = track.current;
      if (!canvas || !el) return;
      const ctx = canvas.getContext("2d", { alpha: false });
      if (!ctx) return;

      // Cover-fit the frame into the canvas box, matching object-cover.
      const draw = (index: number) => {
        const img = framesRef.current[index];
        if (!img?.width) return;
        const dpr = Math.min(window.devicePixelRatio || 1, 2);
        const cw = canvas.clientWidth;
        const ch = canvas.clientHeight;
        if (canvas.width !== Math.round(cw * dpr)) {
          canvas.width = Math.round(cw * dpr);
          canvas.height = Math.round(ch * dpr);
        }
        const scale = Math.max(cw / img.width, ch / img.height);
        const w = img.width * scale;
        const h = img.height * scale;
        ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
        ctx.drawImage(img, (cw - w) / 2, (ch - h) / 2, w, h);
        drawnRef.current = index;
      };

      // Declared before render because render reads it, assigned after because
      // it's render that it's built with. ScrollTrigger can call onUpdate
      // synchronously from inside create() — it does whenever the trigger is
      // built while the page is already scrolled into its range, i.e. a revisit
      // or a restored scroll position — and that call used to land on `st`
      // before its initialiser had run, throwing "Cannot access 'st' before
      // initialization" and taking the rest of this setup (the catch-up hook and
      // the resize listener) with it, so the hero stopped scrubbing entirely.
      // Null until assigned, which reads as progress 0 — the poster frame, which
      // is what's on screen at that instant anyway.
      let st: ScrollTrigger | null = null;

      // Draw the frame the scroll position asks for, or the newest one decoded
      // if the sequence hasn't got that far yet. Clamping forward-only is what
      // makes a partial sequence usable: the hero stalls on its latest frame
      // instead of snapping back to a stale earlier one.
      const render = () => {
        const want = Math.round((st?.progress ?? 0) * (count - 1));
        const i = Math.max(0, Math.min(want, count - 1, readyUpToRef.current));
        if (i !== drawnRef.current) draw(i);
      };

      st = ScrollTrigger.create({
        trigger: el,
        start: "top top",
        end: "bottom bottom",
        onUpdate: render,
      });

      render();
      catchUpRef.current = render;

      const onResize = () => {
        // Force a re-fit: clientWidth changed, so the cached canvas backing
        // size and the cover scale are both stale.
        canvas.width = 0;
        draw(drawnRef.current < 0 ? 0 : drawnRef.current);
      };
      window.addEventListener("resize", onResize);

      return () => {
        catchUpRef.current = null;
        st?.kill();
        window.removeEventListener("resize", onResize);
      };
    },
    { dependencies: [ready, count], scope: track },
  );

  return (
    <>
      {/* Loading gate — fixed to the viewport (not this section), so it
          covers the whole page regardless of where DivisionHero sits in the
          tree. Fades out once every frame has decoded; see the file header
          for why the whole page waits on this rather than just the hero. */}
      <div
        aria-hidden={ready}
        className={`fixed inset-0 z-[100] flex flex-col items-center justify-center gap-5 bg-navy transition-opacity duration-500 ${
          ready ? "pointer-events-none opacity-0" : "opacity-100"
        }`}
      >
        <img
          src="/logo.webp"
          alt=""
          width={462}
          height={200}
          className="h-9 w-auto object-contain"
        />
        <div className="h-0.5 w-40 overflow-hidden rounded-full bg-paper/15">
          <div
            className="h-full bg-green transition-[width] duration-200 ease-out"
            style={{ width: `${Math.round(progress * 100)}%` }}
          />
        </div>
        <p className="font-mono text-[0.62rem] uppercase tracking-[0.2em] text-paper/50">
          Loading {Math.round(progress * 100)}%
        </p>
      </div>

      <section
        ref={track}
        className="relative h-[260vh] motion-reduce:h-svh"
        aria-label={`${name} — scroll-driven hero`}
      >
        {/* svh, not vh: on a phone 100vh is the height with the browser toolbars
          retracted, so the stage runs *under* them and anything parked at its
          foot — the scroll cue — sits below the visible area until you scroll.
          svh is the smallest (toolbars showing) viewport, so the cue is on
          screen from the first paint. */}
        <div className="sticky top-0 flex h-svh items-center overflow-hidden lg:items-end">
          {/* Poster: the first frame, shown until the sequence is decoded. */}
          <img
            src={src(0)}
            alt={name}
            fetchPriority="high"
            className={`absolute inset-0 h-full w-full object-cover transition-opacity duration-500 ${
              ready ? "opacity-0" : "opacity-100"
            }`}
          />
          <canvas
            ref={canvasRef}
            aria-hidden
            className={`absolute inset-0 h-full w-full transition-opacity duration-500 ${
              ready ? "opacity-100" : "opacity-0"
            }`}
          />

          <div
            ref={copyRef}
            className="relative mx-auto w-full max-w-[1600px] px-6 text-center will-change-transform md:px-10 lg:pb-52 xl:pb-60"
          >
            {children ?? (
              <>
                <h1
                  className={`mx-auto max-w-4xl font-display text-[clamp(2.5rem,1rem+5vw,5.5rem)] font-semibold leading-[1.03] tracking-[-0.02em] lg:flex lg:min-h-[2lh] lg:flex-col lg:justify-end ${
                    dark ? "text-ink" : "text-paper"
                  }`}
                  style={{
                    textShadow: dark
                      ? "0 1px 24px rgba(247,245,242,0.75)"
                      : "0 2px 30px rgba(9,33,44,0.45)",
                  }}
                >
                  {head}
                  {tail && <span className="text-green-dark">{tail}</span>}
                </h1>
                <p
                  className={`mx-auto mt-6 max-w-2xl text-lg leading-relaxed md:text-xl ${
                    dark ? "text-ink/75" : "text-paper"
                  }`}
                  style={{
                    textShadow: dark
                      ? "0 1px 18px rgba(247,245,242,0.8)"
                      : "0 1px 18px rgba(9,33,44,0.55)",
                  }}
                >
                  {tagline}
                </p>
              </>
            )}
          </div>

          {/* Scroll cue — mouse outline with a drifting wheel dot, parked at the
            foot of the stage rather than under the copy, so it reads as a
            viewport affordance instead of part of the heading block. */}
          <div
            ref={cueRef}
            aria-hidden
            className={`absolute bottom-8 left-1/2 -translate-x-1/2 md:bottom-10 ${
              dark ? "text-ink/60" : "text-paper/80"
            }`}
          >
            <span className="flex h-10 w-6 items-start justify-center rounded-full border-2 border-current pt-2">
              <span className="block h-1.5 w-1 rounded-full bg-current animate-scroll-cue motion-reduce:animate-none" />
            </span>
          </div>
        </div>
      </section>
    </>
  );
}
